"""Change reminder_time to TIME field

Revision ID: 2dd0c4811dea
Revises: ca1b08afd69b
Create Date: 2025-03-17 17:38:45.800055

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2dd0c4811dea'
down_revision = 'ca1b08afd69b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medication_reminders', schema=None) as batch_op:
        batch_op.alter_column('reminder_time',
               existing_type=mysql.DATETIME(),
               type_=sa.Time(),
               existing_nullable=False)
        batch_op.create_index('idx_reminder_time', ['reminder_time'], unique=False)
        batch_op.create_index('idx_user_id', ['user_id'], unique=False)
        batch_op.create_index('idx_user_medicine_id', ['user_medicine_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medication_reminders', schema=None) as batch_op:
        batch_op.drop_index('idx_user_medicine_id')
        batch_op.drop_index('idx_user_id')
        batch_op.drop_index('idx_reminder_time')
        batch_op.alter_column('reminder_time',
               existing_type=sa.Time(),
               type_=mysql.DATETIME(),
               existing_nullable=False)

    # ### end Alembic commands ###
