"""Add receive_sms_reminders column to users

Revision ID: 59fb7f6fb84e
Revises: 66dc88b72104
Create Date: 2025-03-21 08:56:49.158761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59fb7f6fb84e'
down_revision = '66dc88b72104'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receive_sms_reminders', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('receive_sms_reminders')

    # ### end Alembic commands ###
