"""Added MedicationReminder model and related changes

Revision ID: ca1b08afd69b
Revises: 5e63eefc17ff
Create Date: 2025-03-16 09:58:51.954480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca1b08afd69b'
down_revision = '5e63eefc17ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medication_reminders', schema=None) as batch_op:
        batch_op.drop_constraint('medication_reminders_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('medication_reminders_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'user_medicines', ['user_medicine_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medication_reminders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('medication_reminders_ibfk_1', 'user_medicines', ['user_medicine_id'], ['id'])
        batch_op.create_foreign_key('medication_reminders_ibfk_2', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
